name: redset build only

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [Debug, Release]

    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: redset
          fetch-depth: 0

      - name: get deps
        uses: ecp-veloc/github-actions/get-scr-os-deps@main
        with:
          os: ${{ matrix.os }}

      - name: install kvtree
        uses: ecp-veloc/github-actions/build-ecp-veloc-component@main
        with:
          component: kvtree

      - name: install rankstr
        uses: ecp-veloc/github-actions/build-ecp-veloc-component@main
        with:
          component: rankstr

      - name: build static
        uses: ecp-veloc/github-actions/cmake-build-static@main
        with:
          component: redset
          target: ${{ matrix.target }}

      - name: build only
        uses: ecp-veloc/github-actions/cmake-build-only@main
        with:
          component: redset
          target: ${{ matrix.target }}
